In [1]:
import numpy as np

In [3]:
X= np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [5]:
def sig(z):
  return 1/(1+ np.exp(-z))

In [10]:
weights= 2* np.random.random((2, 1)) - 1
bias= 2 * np.random.random(1) - 1
weights, bias

(array([[ 0.8245029 ],
        [-0.43778652]]),
 array([0.95822464]))

In [11]:
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.72276621],
       [0.62725021],
       [0.85603334],
       [0.79330132]])