In [1]:
import numpy as np

In [3]:
X= np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [5]:
def sig(z):
  return 1/(1+ np.exp(-z))

In [13]:
wh = 2* np.random.random((2, 2)) - 1
bh= 2 * np.random.random((1, 2)) - 1
wo= 2 * np.random.random((2, 1)) - 1 
bo= 2 * np.random.random((1, 1)) - 1                        
wh, bh, wo, bo

(array([[-0.90040719,  0.61815731],
        [ 0.78592199,  0.67624366]]),
 array([[-0.72459274,  0.00300984]]),
 array([[0.19797017],
        [0.6469548 ]]),
 array([[0.85257991]]))

In [15]:
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + b0)
output

array([[0.72276621],
       [0.62725021],
       [0.85603334],
       [0.79330132]])