In [1]:
import numpy as np

In [2]:
X= np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
  return 1/(1+ np.exp(-z))

In [4]:
def derivativeSig(z):
  return sig(z)*(1 - sig(z))

In [19]:
weights = 2* np.random.random((2, 1)) - 1
bias= 2 * np.random.random(1) - 1
lr= 0.1
weights, bias

(array([[ 0.61978424],
        [-0.08096522]]),
 array([-0.46454729]))

In [17]:
for iter in range(10000):
  output0 = X
  output = sig(np.dot(output0, weights) + bias)
  first_term= output - Y
  input_for_last_layer= np.dot(output0, weights) + bias
  second_term= derivativeSig(input_for_last_layer)
  first_two = first_term * second_term
  first_two.shape
  changes= np.array([[0.0], [0.0]])
  for i in range(2):
    for j in range(4):
      changes[i][0] += first_two[j][0] * output0[j][i]
  weights= weights - lr*changes
  bias_change= 0.0
  for j in range(4):
    bias_change += first_two[j][0] * 1
  bias= bias - lr * bias_change 
output= sig(np.dot(X, weights) + bias) 
weights, bias, output

(array([[5.59483923],
        [5.59483922]]),
 array([-8.48445374]),
 array([[2.06613559e-04],
        [5.26693487e-02],
        [5.26693490e-02],
        [9.37334239e-01]]))

In [20]:
for iter in range(10000):
  output0 = X
  output = sig(np.dot(output0, weights) + bias)
  first_term= output - Y
  input_for_last_layer= np.dot(output0, weights) + bias
  second_term= derivativeSig(input_for_last_layer)
  first_two = first_term * second_term
  first_two.shape
  changes= np.dot(output0.T, first_two)
  
  weights= weights - lr*changes
  bias_change= np.sum(first_two)
  bias= bias - lr * bias_change 
output= sig(np.dot(X, weights) + bias) 
weights, bias, output

(array([[5.48098768],
        [5.48098767]]),
 array([-8.31416669]),
 array([[2.44960965e-04],
        [5.55573562e-02],
        [5.55573571e-02],
        [9.33875800e-01]]))