In [9]:
import numpy as np

In [10]:
X= np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,1,1,0]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [11]:
def sig(z):
  return 1/(1+ np.exp(-z))

In [12]:
def derivativeSig(z):
  return sig(z)*(1 - sig(z))

In [13]:
wh = 2* np.random.random((2, 2)) - 1
bh= 2 * np.random.random((1, 2)) - 1
wo= 2 * np.random.random((2, 1)) - 1 
bo= 2 * np.random.random((1, 1)) - 1   
lr= 0.1                     
wh, bh, wo, bo

(array([[-0.8143549 ,  0.95115382],
        [-0.73774633,  0.06298741]]),
 array([[ 0.01594752, -0.56386114]]),
 array([[ 0.62813529],
        [-0.08490347]]),
 array([[-0.9278449]]))

In [14]:
for itern in range(10000):
    output0 = X
    inputHidden= np.dot(output0, wh) + bh
    outputHidden = sig(inputHidden)
    inputForOutputLayer = np.dot(outputHidden, wo) + bo
    output= sig(inputForOutputLayer)

    first_term_output_layer= output - Y
    second_term_output_layer= derivativeSig(inputForOutputLayer)
    first_two_output_layer= first_term_output_layer*second_term_output_layer

    first_term_hidden_layer= np.dot(first_two_output_layer, wo.T)
    secon_term_hidden_layer= derivativeSig(inputHidden)
    first_two_hidden_layer= first_term_hidden_layer * secon_term_hidden_layer

    changes_output= np.dot(outputHidden.T, first_two_output_layer)
    changes_output_bias= np.sum(first_two_output_layer, axis = 0, keepdims=True)

    changes_hidden= np.dot(output0.T, first_two_hidden_layer)
    changes_hidden_bias= np.sum(first_two_hidden_layer, axis = 0, keepdims=True)

    wo= wo - lr*changes_output
    bo= bo - lr*changes_output_bias

    wh= wh - lr*changes_hidden
    bh= bh - lr*changes_hidden_bias
output0 = X
inputHidden= np.dot(output0, wh) + bh
outputHidden = sig(inputHidden)
inputForOutputLayer = np.dot(outputHidden, wo) + bo
output= sig(inputForOutputLayer)
output, wh, bh, wo, bo


(array([[0.12982703],
        [0.87665073],
        [0.87673301],
        [0.15236253]]),
 array([[-3.55037066,  5.68482647],
        [-3.54788897,  5.67047589]]),
 array([[ 5.27315254, -2.3265452 ]]),
 array([[5.43352506],
        [5.31083849]]),
 array([[-7.78068591]]))